service: lambda-docker-serverless-nestjs-prisma
frameworkVersion: '4'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  ecr:
    images:
      baseimage:
        path: ./

functions:
  api:
    name: lambda-docker-serverless-nestjs-prisma
    image: baseimage 
    events:
      - httpApi:
          path: /api
          method: GET
